### ISSUE TITLE
Training and environment files

### ISSUE THREAD

**Issue by botaoye** [kxhit/zero123-hf#1]
Hi author, thank you for your excellent work. I found the `environment.yml` and the training code `train_zero1to3.py` in ReadMe, but they are unavailable now. Will they be available later?

**Comment by kxhit** [comment]
Hi, yes the training script is still tuning. I need some time to verify the script can produce similar training results to the original one. I will update when it's ready!

**Comment by botaoye** [comment]
Thank you for your reply. Looking forward to your results.
