### ISSUE TITLE
ValueError: cc_projection/pipeline_zero1to3.py as defined in `model_index.json` does not exist in kxic/zero123-165000 and is not a module in 'diffusers/pipelines'.

### ISSUE THREAD

**Issue by Magicboomliu** [kxhit/zero123-hf#11]
It seems that when I run the `test_zero1to3.py`, there seems to show an error like this, is it something wrong with the huggingface repo?

**Comment by kxhit** [comment]
Hi, I just checked and it works fine on my side. Could you provide more details e.g., environment, hf version?

**Comment by xdobetter** [comment]
> It seems that when I run the `test_zero1to3.py`, there seems to show an error like this, is it something wrong with the huggingface repo?

I found that the reason for this is the diffusers version mismatch.
Using the version in requirements.txt I found it worked
```bash
pip install diffusers==0.18.2
```
