### ISSUE TITLE
DDPMScheduler or DDIMScheduler is used?

### ISSUE THREAD

**Issue by YuxuanSnow** [kxhit/zero123-hf#12]
Hi,

thanks for the great implementation.

I have a small question regarding the scheduler used in training. In the training script, the DDPMScheduler is used as here: 
https://github.com/kxhit/zero123-hf/blob/master/train_zero1to3.py#L571

However, in the huggingface checkpoint, it says the DDIMScheduler is used: https://huggingface.co/kxic/zero123-xl/blob/main/scheduler/scheduler_config.json. 

I wonder if you could give me a confirmation on which scheduler is used in training and inference? Or for huggingface library if i do DDPMScheduler.from_pretrained('kxic/zero123-xl', subfolder="scheduler"), still the DDIM scheduler used in checkpoint will be loaded?

**Comment by kxhit** [comment]
Hi, in training, DDPM is used and in testing, DDIM is used. I think this is a default setting for the most stable diffusion models. I'm not an expert in noise scheduler, but happy to have discussions!

**Comment by YuxuanSnow** [comment]
Thanks for the answer. It sounds reasonable that use DDPM during training and DDIM during inference. However i wonder why don't directly use the DDIM in the training since the training objective for DDIM and DDPM is the same? Currently, the saved checkpoint calls the DDPM classes as scheduler during inference if people directly load the pipeline.
