### ISSUE TITLE
convert_zero123_to_diffusers error 

### ISSUE THREAD

**Issue by icedCoffe001** [kxhit/zero123-hf#15]
After run  diffusers/scripts/convert_zero123_to_diffusers.py , i got a dir like this.
![1715287875682](https://github.com/kxhit/zero123-hf/assets/116945973/9f092dec-7fc8-49c3-9ef8-b73be5235c7e)
But when i want to use it in diffusers like this, it is report an Error.
`pipe = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
	"./model/zero1to3",
 	controlnet=controlnet, torch_dtype=torch.float16,
	local_files_only = True
)`
>  ValueError: Pipeline <class 'diffusers.pipelines.controlnet.pipeline_controlnet_img2img.StableDiffusionControlNetImg2ImgPipeline'> expected {'text_encoder', 'scheduler', 'feature_extractor', 'safety_checker', 'vae', 'controlnet', 'unet', 'tokenizer'}, but only {'scheduler', 'feature_extractor', 'controlnet', 'vae', 'unet'} were passed.

Any help would be greatly appreciated!

**Comment by icedCoffe001** [comment]
Can this be loaded only by pipeline_zero1to3?

**Comment by kxhit** [comment]
Hi, yes it should be loaded by pipeline_zero1to3

**Comment by icedCoffe001** [comment]
Thank you!
