### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by lirus7** [kxhit/zero123-hf#2]
Hey!
Thanks for taking up this initiative.
I wanted to know when will the training script be released publicly?

**Comment by kxhit** [comment]
Thank you for your interest! I'm actively working on verifying the training implementation to ensure alignment with the original settings. I'm considering an initial release of the script that would allow everyone to try it out and contribute to its refinement. I anticipate this release within the next couple of weeks. Your input is highly appreciated, and I'll provide updates as I make progress.

**Comment by lirus7** [comment]
Thanks for the response. Looking forward to contributing.

**Comment by lirus7** [comment]
Will keep this open. You can close it once you release it :)

**Comment by Xiashangning** [comment]
Hi, super thanks to your great initiative!
Do you have any updates on the training script?

**Comment by kxhit** [comment]
Hi @lirus7 @Xiashangning 
The training script is just released. Please let me know if it works well! Cheers!

**Comment by Xiashangning** [comment]
Great! Will test it asap
Thanks a lot
