### ISSUE TITLE
Problems about fine-tuning from zero123-xl.ckpt

### ISSUE THREAD

**Issue by AbrahamYabo** [kxhit/zero123-hf#3]
Noticing that the code of Load scheduler and models use args.pretrained_model_name_or_path to load DDPM, CLIP, and so on from huggingface.co/models. How could zero123-hf tune a model from ckpt provided by zero123 like 105000.ckpt 165000.ckpt or zero123-xl.ckpt

**Comment by AbrahamYabo** [comment]
Thanks, We have found kxic/zero123-xl  https://huggingface.co/kxic/zero123-xl as

**Comment by AbrahamYabo** [comment]
But Connot load the ckpt from kxic/zero123-xl. Here are the tracebacks
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ma-user/work/Diffusion/zero123-hf/train_zero1to3.py:1042 in <module>          │
│                                                                                                  │
│   1039                                                                                           │
│   1040 if __name__ == "__main__":                                                                │
│   1041 │   args = parse_args()                                                                   │
│ ❱ 1042 │   main(args)                                                                            │
│   1043                                                                                           │
│                                                                                                  │
│ /home/ma-user/work/Diffusion/zero123-hf/train_zero1to3.py:575 in main               │
│                                                                                                  │
│    572 │   image_encoder = CLIPVisionModelWithProjection.from_pretrained(args.pretrained_model_  │
│    573 │   #feature_extractor = None #CLIPFeatureExtractor.from_pretrained(args.pretrained_mode  │
│    574 │   feature_extractor = CLIPFeatureExtractor.from_pretrained(args.pretrained_model_name_  │
│ ❱  575 │   vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="v  │
│    576 │   unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subf  │
│    577 │                                                                                         │
│    578 │   vae.train()                                                                           │
│                                                                                                  │
│ /home/ma-user/work/Conda-zero123/lib/python3.8/site-packages/diffusers/models/modeling_util │
│ s.py:567 in from_pretrained                                                                      │
│                                                                                                  │
│   564 │   │   │   │   │   # move the params from meta device to cpu                              │
│   565 │   │   │   │   │   missing_keys = set(model.state_dict().keys()) - set(state_dict.keys(   │
│   566 │   │   │   │   │   if len(missing_keys) > 0:                                              │
│ ❱ 567 │   │   │   │   │   │   raise ValueError(                                                  │
│   568 │   │   │   │   │   │   │   f"Cannot load {cls} from {pretrained_model_name_or_path} bec   │
│   569 │   │   │   │   │   │   │   f" missing: \n {', '.join(missing_keys)}. \n Please make sur   │
│   570 │   │   │   │   │   │   │   " `low_cpu_mem_usage=False` and `device_map=None` if you wan   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from ./kxic/zero123-xl/ because the following keys are missing: 
 encoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.proj_attn.bias, decoder.mid_block.attentions.0.key.weight, 
encoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.proj_attn.weight, 
encoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.proj_attn.bias, 
encoder.mid_block.attentions.0.proj_attn.weight, decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.value.weight. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomely initialize those weights or else make sure your checkpoint file is correct.
[14:38:26] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 4162585) of binary: /home/ma-user/work/yabo/Conda-zero123/bin/python                                            api.py:671

**Comment by kxhit** [comment]
Hi for finetuning from Zero123 ckpt. 
1. Modify the `--pretrained_model_name_or_path kxic/zero123-xl` or  `--pretrained_model_name_or_path kxic/zero123-105000`
2. And take care of this part [code](https://github.com/kxhit/zero123-hf/blob/fe7762e6df676a08777f79f7e6f7f6db46b4eb4a/train_zero1to3.py#L582) as the zero123 ckpt already 8 channels in.

Please let me know if it still does not work.

**Comment by AbrahamYabo** [comment]
Thanks for your quick response. That really helps me a lot. Thank you so much!!
