### ISSUE TITLE
Is this released model the same as the official one?

### ISSUE THREAD

**Issue by ewrfcas** [kxhit/zero123-hf#6]

**Comment by kxhit** [comment]
The checkpoint is converted from the original one and the pipeline implementation strictly follows the original implementation but using diffusers lib. From the inference results and the initial state of training, it looks very consistent with the original one. As the different lib (diffusers v.s original Pytorch lightning) may have different behaviors in some cases, I think they should give pretty much the same results, while I don't know how to strictly verify.

**Comment by ewrfcas** [comment]
Thanks. I just tested the code on Objaravse. But the results are a little strange. I will debug about it.

**Comment by ewrfcas** [comment]
I have addressed the problem, which is caused by the wrong usage of masking.

**Comment by kxhit** [comment]
Great! Feel free to raise any issues if you find something is incorrect!
