### ISSUE TITLE
Minimum requirements for fine-tune from zero123-xl.ckpt

### ISSUE THREAD

**Issue by gitsawww** [kxhit/zero123-hf#8]
Thanks for this great work !! Do you know if I want fine-tune from zero123-xl.ckpt, how many 3090s are needed at least? And what are the corresponding vram and ram?Thanks a lot.

**Comment by kxhit** [comment]
Hi, sorry I don't know much details of training xl version. You might look at objaverse-xl paper or open an issue at original zero123 repo.
I think xl version is the same archetecture of this normal one, just be trained with more objaverse data. I don't know what's your finetuning goal of zero123? If you need tune the whole UNet params, that's pretty much the same setting for [training zero123](https://github.com/kxhit/zero123-hf/issues/5#issuecomment-1712791624). But finetuning might need fewer batch size. 
Hope it helps!

**Comment by gitsawww** [comment]
Thank you for your reply! I currently have a set of my own data, and I want to finetune it on zero123's ckpt, and want to improve its performance in the aspect where the data is located. Currently, I only have one 3090, and it shows a video memory error. I want to know the specific minimum graphics card I need.The data is about 50g in size.

**Comment by kxhit** [comment]
As far as I know, A100 80GB is preferred.
