### ISSUE TITLE
Stable-Zero123

### ISSUE THREAD

**Issue by huanngzh** [kxhit/zero123-hf#9]
How about converting [Stable-Zero123](https://huggingface.co/stabilityai/stable-zero123) into a diffusers pipeline?

**Comment by huanngzh** [comment]
https://github.com/threestudio-project/threestudio/tree/main/extern/ldm_zero123

**Comment by kxhit** [comment]
Hi, it looks exactly the same as the original zero123. Please correct me if this is another paper/work.

**Comment by huanngzh** [comment]
It looks basically the same, except that the training data is replaced and the relative distance of the original zero123 is replaced by the elevation of the input image. I think it would be better if there is a huggingface repo like (kxic/zero123-xl)[https://huggingface.co/kxic/zero123-xl].

**Comment by kxhit** [comment]
Hi @huanngzh 

The Stable-zero123 inference is now supported. Run `test_zero1to3` with model_id `kxic/stable-zero123` should work! 

#https://github.com/kxhit/zero123-hf/commit/decfca77916985dc0de9a13f176f8666ebd9fac3
